# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SurveyBeats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'CMPageControl'
  # Pods for SurveyBeats

  target 'SurveyBeatsTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'SurveyBeatsUITests' do
    inherit! :search_paths
    use_frameworks!
    pod 'SDWebImage'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'CMPageControl'
  end

end
