# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Unit_test, code_coverage"
  lane :development do
    scan(
       scheme: "SurveyBeats",
       clean: true,
       code_coverage: true,
       device: "iPhone 6s",
   )
    slather(
       input_format: "auto",
       scheme: "SurveyBeats",
       workspace: "SurveyBeats.xcworkspace",
       proj: "SurveyBeats.xcodeproj",
       output_directory: "Slather",
       html: true,
       show: true,
   )
  end
end
